class Kkc < Formula
  desc "Dual-panel file manager inspired by Norton Commander, written in Rust"
  homepage "https://github.com/redbug26/kkc-rust"
  version "0.1.14"
  license "MIT"

  # Pre-built binaries are updated automatically on each tagged release.
  # SHA256 values below are regenerated by the release workflow.
  on_macos do
    url "https://github.com/redbug26/kkc-rust/releases/download/v#{version}/kkc-macos-arm64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  on_linux do
    url "https://github.com/redbug26/kkc-rust/releases/download/v#{version}/kkc-linux-x86_64.tar.gz"
    sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  end

  # Build from source with: brew install --HEAD redbug26/kkc-rust/kkc
  head do
    url "https://github.com/redbug26/kkc-rust.git", branch: "main"
    depends_on "rust" => :build
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args
    else
      bin.install "kkc"
    end
  end

  test do
    assert_predicate bin/"kkc", :exist?
  end
end
